; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; 指定分区表
board_build.partitions = partitions.csv

; 使用platformio自带的烧录按键（"->"键）进行OTA下载
; 首次用USB下载时，以下两条应打上注释
; 以后使用OTA下载，取消注释
upload_protocol = custom
upload_command = python ota_upload.py $SOURCE